[en]
  title = "Yaya's World"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"

[jp]
  title = "やよいのWORLD"
  languageName = "日本語"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/jp"
