[[main]]
  identifier = "adventures"
  name = "Adventures"
  url = "adventures"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "Peektures"
  url = "gallery"
  weight = 2

[[main]]
  identifier = "guides"
  name = "Fiesta Guides"
  url = "fiesta"
  weight = 1
